---@class CCallback
---@field _CALLBACK 'ox_lib'|'native'
---@field _VERSION string
---@field getcallback fun(): 'ox_lib'|'native'
---@field getversion fun(): string
---@field register fun(name: string, cb: fun(...): any)
---@field trigger fun(name: string, cb: (fun(...): any), ...: any) @client-side only
---@field await fun(name: string, ...: any): ... @client-side only
---@field trigger fun(player: integer|string, name: string, cb: (fun(...): any), ...: any) @server-side only
---@field await fun(player: integer|string, name: string, ...: any): ... @server-side only