---@class CNotify
---@field getname fun(): 'qb-core'|'es_extended'|'native'
---@field getversion fun(): string
---@field text fun(player: string|integer, text: string, _type: 'error'|'success'|'primary'?, time: integer?)
---@field item fun(player: string|integer, item: string, amount: integer?, text: string?)
---@field text fun(text: string, _type: 'error'|'success'|'primary'?, time: integer?)
---@field item fun(item: string, amount: integer?, text: string?)