---@class CDoorlock
---@field getname fun(): 'ox_doorlock'|'qb-doorlock'
---@field getversion fun(): string
---@field setstate fun(player: integer|string, door_id: string, state: boolean, picked: boolean?)